import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "@/components/nav/navBar";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import MouseBlobs from "@/components/MouseBlobs";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const tagesschrift = localFont({
  src: "../public/fonts/Tagesschrift-Regular.ttf", // path ကိုသေချာကြည့်
  variable: "--font-tagesschrift",
  display: "swap",
});

const AlumniSansInlineOne = localFont({
  src: "../public/fonts/AlumniSansInlineOne-Regular.ttf",
  variable: "--font-alumni-sans-inline-one",
  display: "swap",
});

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} ${tagesschrift.variable}  ${AlumniSansInlineOne.variable} `}
      style={{ filter: "invert(0)" }}
    >
      <body>
        <main className="relative flex min-h-screen flex-col items-center justify-between bg-gray-700 overflow-hidden">
          <MouseBlobs />
          <div className="relative z-30 w-full max-w-[1280px]">
            <NavBar />
            {/* {children} */}
          </div>

          <Toaster position="top-center" richColors closeButton />
        </main>
      </body>
    </html>
  );
}