import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "@/components/nav/navBar";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import MouseBlobs from "@/components/MouseBlobs";

// Font setup
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const tagesschrift = localFont({
  src: "../public/fonts/Tagesschrift-Regular.ttf",
  variable: "--font-tagesschrift",
  display: "swap",
});

const AlumniSansInlineOne = localFont({
  src: "../public/fonts/AlumniSansInlineOne-Regular.ttf",
  variable: "--font-alumni-sans-inline-one",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} ${tagesschrift.variable} ${AlumniSansInlineOne.variable}`}
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="relative flex min-h-screen flex-col items-center justify-between bg-[#F9F9F9]/80 dark:bg-[#1D1D1F]/80 backdrop-blur-lg text-[#1D1D1F] dark:text-[#F9F9F9] overflow-hidden">
            <div className="relative z-30 w-full max-w-[1280px]">
              <NavBar />
              {/* <MouseBlobs /> */}
              {children}
            </div>
            <Toaster position="top-center" richColors closeButton />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
